### ISSUE TITLE
Not enough gpu memory for verification

### ISSUE THREAD

**Issue by LYX-ll** [robotic-vision-lab/Dual-Interactive-Implicit-Neural-Network#10]
Hi, during training, it is normal to process 800 training sets, but due to our limited gpu, processing 100 validation sets always prompts insufficient gpu memory. Is there a solution for this, thank you very much!

**Comment by LYX-ll** [comment]
Thank you for your reply, but I have a problem.
I set 'eval_bsize' and 'bsize' to 2, it reports an error:
`RuntimeError: Calculated padded input size per channel: (96 x 0). Kernel size: (1 x 1). Kernel size can't be greater than actual input size`

**Comment by hquan7395** [comment]
It's hard for me to troubleshoot with just this error. Just to confirm, I recommended the 'bsize' argument in the 'forward' method of DIINN. 
Here's an example:

`output_size = (512, 512) #the super-resolved image have 512x512 pixels, and your memory is not enough`
`bsize = 10000 #this means the decoder only make predictions on 10000 pixels at a time, till all 512x512 are done`

`sr_image = model(lr_image, output_size, bsize)`

Hope this helps. Please keep me posted.
