### ISSUE TITLE
Pre-trained model of DIIN

### ISSUE THREAD

**Issue by WinstonHuTiger** [robotic-vision-lab/Dual-Interactive-Implicit-Neural-Network#2]
Hi @hquan7395 , thank you so much for open-sourcing this project.  I just want to test on my own data samples, but training 1000 epochs on my computer requires nearly 4 days. So, could you please provide a pre-trained model of your DIIN network?

**Comment by hquan7395** [comment]
Hi @WinstonHuTiger , thank you for your interest in our work. We're working on an internal server at our lab to host what we published and that might take a little while. I'll be happy to share the pretrained model with you (probably via my personal Google Drive, so please be considerate).

**Comment by WinstonHuTiger** [comment]
@hquan7395 Thank you so much for sharing this file with me.

**Comment by hquan7395** [comment]
Thanks again for your interest in our work. Do feel free to let me know if you encounter any problem with testing with the checkpoint. I'll close this issue for now.
