### ISSUE TITLE
Training time and GPU setup?

### ISSUE THREAD

**Issue by jaroslawjanas** [robotic-vision-lab/Dual-Interactive-Implicit-Neural-Network#3]
Hi guys,
Fantastic work and a very interesting read,

What kind of hardware did you use to train this model? Number of GPUs and their model?
And for how long (hours, days) you trained it?

**Comment by hquan7395** [comment]
Hi @jaroslawjanas,

Thank you for your interest in our work. We were fortunate to have access to a cluster with 4 A100 GPUs machine. The training time took around 6~7 hours.
