### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by DorArv** [robotic-vision-lab/Dual-Interactive-Implicit-Neural-Network#7]
Hello,

we carefully followed the instructions you provided in the readme file, and yet got errors when trying to train the model (running train.py), this probably stems from the libraries and packages versions that don't match one another... can you please provide the yml environment file you worked with, or mention the versions of the main libraries in the code?

Thanks.

**Comment by hquan7395** [comment]
We recently created a new branch 'update' that allows our projects to run on newer versions of the required libraries.
