### ISSUE TITLE
About channel

### ISSUE THREAD

**Issue by XLR-man** [robotic-vision-lab/Dual-Interactive-Implicit-Neural-Network#8]
Hi
your code is based on RGB images. But i want to use the code in one channel images，can i directly change the datasets and train in your code？ Or should i change your code about channel to fit my need？

**Comment by hquan7395** [comment]
Hi, thank your for your interest in our project!

To use the code for one channel images, you'll need to change the code to accept it, specifically the encoder module (RDN) construction (see lines 108-119 in src/models/components/rdn.py).

Changing line 118 in src/models/components/rdn.py) from:
```
args.n_colors = 3
```
to:
```
args.n_colors = 1
```
should do.

Please also try our newer branch 'update' and let us know if you encounter any other problems.

**Comment by XLR-man** [comment]
Thank you! I will try
